### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by vrs42** [dhogaza/os8pip#1]
Got the following errors building on Debian for Windows 10 WSL:
cc     os8pip.c   -o os8pip
os8pip.c:49:33: error: initializer element is not constant
 const unsigned DECTAPE_BLOCKS = OS8_DECTAPE_LENGTH / (OS8_BLOCK_SIZE * 2);
                                 ^~~~~~~~~~~~~~~~~~
os8pip.c: In function ‘main’:
os8pip.c:2076:9: warning: implicit declaration of function ‘flock’ [-Wimplicit-function-declaration]
     if (flock(os8_file, LOCK_EX | LOCK_NB) == -1) {
         ^~~~~

The following patch was sufficient to get things going:
[patch.txt](https://github.com/dhogaza/os8pip/files/8360358/patch.txt)

Thanks!

Vince

**Comment by dhogaza** [comment]
I can't read your patch but I changed some "const int" definitions to #define rather than fight compilers and their C dialect implementations.  I also included sys/files.h which should fix the problem for your linux compiler.  Apparently in OS/X another header included it or otherwise correctly defined flock().

Let me know if it compiles for you now.

**Comment by vrs42** [comment]
Looks like you did some other changes -- I'm getting this now:
os8pip.c: In function ‘file_entry_length’:
os8pip.c:510:10: note: the ABI of passing struct with a flexible array member has changed in GCC 4.4
 unsigned file_entry_length(dir_struct_t dir_struct)
          ^~~~~~~~~~~~~~~~~
Only a 'note' level warning, though, so I'm not sure it's worth fiddling with it.

Vince

**Comment by dhogaza** [comment]
Seriously? 

Does gcc 4.4 have a -std=c11 switch?  That is what I'm compiling with using CLANG, and none of the issues you've pointed out are flagged by CLANG, which is in general much more strict than gcc.

It looks like gcc 4.4 was released in 2012, so is 10 years old.  Will it take std=c11?  gcc is all the way up to version 9 at this point.  In my real life job I am forced to support ancient versions of linux and glibc and the standard C++ library.

But in my private life I think I'm going to suggest updating to a recent version of gcc.

When I wrote this I chose C11 as my target specifically because I'm not all that interested in supporting old versions of gcc or MS C.  

Now I could easily kludge my way around this annoying note message, but it would make the code less obvious.

Making things less obvious is, of course, the Tau of C but I'm trying to avoid that as much as I can.

**Comment by vrs42** [comment]
The -std=c11 flag is accepted, but generates quite a few "implicit declaration" warnings and an error about PATH_MAX being undeclared, all in addition to the note about passing a variable length struct by value.   This is with gcc version:
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

Passing the address of the struct instead does of course avoid triggering the message.

Vince

**Comment by dhogaza** [comment]
Well, sure, and replacing file_entries with a pointer and passing along the address of that would as well.  The code's just not as nice looking.

But of course it is C and the notion of nice-looking code is totally foreign to the concept of the language anyway.  Go's as bad or worse.

The "implicit declarations" warnings and the "PATH_MAX undeclared" error is due to another missing .h file due to differences in OS/X's clib and GNU clib.  I'll track that down.

**Comment by dhogaza** [comment]
I'm including limits.h which is where MAX_PATH is defined ... huh.

**Comment by dhogaza** [comment]
"Passing the address of the struct instead does of course avoid triggering the message."

Passing by value makes it clear when someone reads the function including the call that the callee will not modify the struct being passed.  I can say "const *" in the callee's prototype of course, but then one has to read that code to be sure that the contents of the struct being pointed to isn't modified.

I'll cave in ...

**Comment by dhogaza** [comment]
OK it compiles in gcc 9 now but not with -std=c11 because the calls causing you problems are not part of ISO C 2011 but rather Posix.  Wonderful.  Apparently the header files for Max OS/X don't disable these.

I imagine if you grab the last update and compile using your gcc 6 with no -std=c11 switch it will compile and run fine.

Oh well, I'd been meaning to update VMWare Fusion to 12 to run on OS/X Big Sur anyway.  My work linux VMs are ancient due to having to support customers on ancient linux, big ones, who won't update to any recent linux version.

**Comment by vrs42** [comment]
Compiles with no warnings now.  Thanks!

**Comment by dhogaza** [comment]
I'll close this issue, then.  The next question will be ... does it work?
